import dotenv from 'dotenv';
dotenv.config();

export const PORT = process.env.PORT || 3002;
export const API_KEY = process.env.API_KEY;
export const ELEVENLABS_WEBHOOK_SECRET = process.env.ELEVENLABS_WEBHOOK_SECRET;
export const ELEVENLABS_WEBHOOK_SECRET_COLTEFINANCIERA_RECORDATORIOS = process.env.ELEVENLABS_WEBHOOK_SECRET_COLTEFINANCIERA_RECORDATORIOS;

// Supabase Coltefinanciera Recordatorios
export const SUPABASE_URL_COLTEFINANCIERA_RECORDATORIOS = process.env.SUPABASE_URL_COLTEFINANCIERA_RECORDATORIOS;
export const SUPABASE_KEY_COLTEFINANCIERA_RECORDATORIOS = process.env.SUPABASE_KEY_COLTEFINANCIERA_RECORDATORIOS;